import{test,expect}from'bun:test';
import{selectVideoContract,contract,deliveryPassArguments,validateSourceGeometry,sourceByteCeiling,validateOutput,handleVideo}from'./video.mjs';
import{selectVideoContract as workerSelect,videoOptions}from'../src/lib/video.ts';
import composite from './video-contract-4k-xlarge.json';
const url=composite.source.url;
test('only two composite rows resolve identically while original source cannot request912',()=>{for(const size of['small','xlarge']){const c=selectVideoContract(url,size);expect(c).toEqual(workerSelect(url,size));expect(c.source.provenance.assetId).toBe('a13');expect(c.source.geometry).toEqual({width:3840,height:2160});expect(c.source.bytes).toBe(225659075);}for(const size of[undefined,'large','medium','xsmall','912'])expect(selectVideoContract(url,size)).toBeUndefined();expect(selectVideoContract(contract.source.url,'xlarge')).toBeUndefined();expect(selectVideoContract(url+'?x=1','xlarge')).toBeUndefined();expect(videoOptions({size:'xlarge'}).size).toBe('xlarge');});
test('912 preserves720 bitrate/audio and480control preserves480 settings, with independent input ceiling',()=>{const large=selectVideoContract(url,'xlarge'),small=selectVideoContract(url,'small');expect(large.encoding).toEqual({...contract.encoding,width:1616,height:912,sar:'304:303'});expect(small.encoding).toEqual(selectVideoContract(contract.source.url,'small').encoding);expect(sourceByteCeiling(large)).toBe(268435456);expect(sourceByteCeiling(contract)).toBe(62914560);expect(large.limits.bytes).toBe(62914560);expect(large.limits.encodeMs).toBe(300000);expect(large.limits.jobMs).toBe(600000);const a=deliveryPassArguments('i','o','p',2,large);expect(a[a.indexOf('-vf')+1]).toBe('fps=fps=25/1:round=near,scale=1616:912:flags=lanczos,setsar=304/303:max=65535');});
test('source geometry remains independently bound and output preserves declared aspect',()=>{const v={width:3840,height:2160,avg_frame_rate:'50/1',r_frame_rate:'50/1'};expect(()=>validateSourceGeometry(v,composite)).not.toThrow();expect(()=>validateSourceGeometry(v,contract)).toThrow();expect(()=>validateSourceGeometry({...v,width:1280,height:720},composite)).toThrow();const source={streams:[{...v,codec_type:'video'},{codec_type:'audio'}],format:{duration:'79.153'}},output={streams:[{codec_type:'video',codec_name:'h264',pix_fmt:'yuv420p',width:1616,height:912,avg_frame_rate:'25/1',r_frame_rate:'25/1',sample_aspect_ratio:'304:303',display_aspect_ratio:'16:9'},{codec_type:'audio',codec_name:'aac',channels:2,sample_rate:'48000'}],format:{duration:'79.168'}};expect(validateOutput(source,output,composite).width).toBe(1616);});
test('ambiguous identity and unapproved exactsource fail before encoder info work',async()=>{for(const query of['source_url='+encodeURIComponent(url)+'&assetId=a13&size=xlarge','source_url='+encodeURIComponent(url)+'&size=large','source_url=https%3A%2F%2Fevil.invalid%2Fa.mp4&size=xlarge']){let code;const res={writeHead(c){code=c;return this;},end(){}};await handleVideo({url:'/video-info?'+query,method:'GET'},res);expect(code).toBe(400);}});
